version: 2.1

orbs:
  go: gotest/tools@0.0.2

workflows:
  version: 2
  ci:
    jobs:
      - lint
      - test-golang-1_9:
          name: test-golang-1.9
      - test-golang-1_10:
          name: test-golang-1.10
      - go/test:
          name: test-golang-1.11
          executor:
            name: go/golang
            tag: 1.11-alpine
      - go/test:
          name: test-golang-1.12
          executor:
            name: go/golang
            tag: 1.12-alpine
          codecov-upload: true

commands:
  install-deps:
    description: Install dep and dependencies
    steps:
      - run:
          name: Install dep
          command: |
            command -v dep && exit
            wget -O- -q https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run:
          name: Install dependencies
          command: dep ensure

jobs:

  lint:
    working_directory: /work
    docker: [{image: 'docker:17.06-git'}]
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker version
      - run:
          name: "Install Dependencies"
          command: |
            docker build --target dev-with-source --tag cli-builder:$CIRCLE_BUILD_NUM .
            docker run --name \
                deps-$CIRCLE_BUILD_NUM cli-builder:$CIRCLE_BUILD_NUM \
                dep ensure
            docker cp \
                deps-$CIRCLE_BUILD_NUM:/go/src/gotest.tools/vendor \
                vendor
      - run:
          name: "Lint"
          command: |
            docker build --target dev-with-source --tag cli-linter:$CIRCLE_BUILD_NUM .
            docker run --rm cli-linter:$CIRCLE_BUILD_NUM

  test-golang-1_9:
    executor:
      name: go/golang
      tag: 1.9-alpine
    steps:
      - checkout
      - install-deps
      - run:
          name: "Unit Test GO 1.9"
          command: |
            go test -v $(go list ./... | grep -v '/vendor/')


  test-golang-1_10:
    executor:
      name: go/golang
      tag: 1.10-alpine
    steps:
      - checkout
      - install-deps
      - run:
          name: go test
          environment:
            GOTESTSUM_JUNITFILE: /tmp/test-reports/unit/junit.xml
          command: |
            mkdir -p /tmp/test-reports/unit
            gotestsum
      - store_test_results:
          path: /tmp/test-reports
